---
dist: xenial
language: python
python: 3.7
services: docker

env:
  global:
    - IMAGE_NAME=dhsncats/code-gov-update
    - DOCKER_USER=jsf9k
    - >
      secure: "WS6nFL47FlKmNth1NKSnuuy+bjHbcs4EDjSJ5RNf+3geQKjldTwpWZm
      +Op1hYdaernZGQ2gDgXaALEFG6QZy44Cn9le6VF7OM+MV8KrsiI3D4b9jdpSHi7U
      21kHBYe87w2f/bi/06uutM+3dq5BbCLF+BUJMmg74oxWUe8ycQOEvGbQeW2KKvcE
      diE8vgiYNAxYQxBXH2EL5NWSksztgPNXrOWAIww5hSTVOriYtl65Xk6d9EDqLPzV
      Sa8jH8dh0ASJ82NJKc4IDUn7eml4T22gin7vsPd3+xUPX6rJ/60weGUXU+SZdHVp
      vk7AEOcNSkNc1/otCM2pzBvHsq25SVFvvFOrjTKGYaWgX+QqKtQTEjODeIOetyfQ
      cQKHbhTQjG2SrDDWMvqd81Y5EmY3HHPuogDXMDPeFarz7YNnjHEweErtDFDkowpC
      hHbjUgl/OomDzqb3DCYzBaa68sS1i8noCk7YtvQGBhb5fuediLEuPrKU5FE7PNX3
      qWIebKFcshS/FZRkpACRgFmIWbuW1SSi214+kL4szMDKsCxW3eiKTowih6EfJJ5+
      O0M4dO23GO15OaJJWrS6ZvUqPR23Ezzyl9K3H+EGJLbcIJOJdLgaUjdk1UqyJ3eF
      tNduoN86qExKnwzeQ4ul0o0Xpfo1pCC/3EfALuqx4SjfnBgq60Jg="

install:
  - pip install --upgrade -r requirements-test.txt
  - travis_scripts/build_docker_image.sh

script:
  - pre-commit run --all-files

deploy:
  - provider: script
    script: travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
      python: '3.7'
