---
dist: xenial
language: python
python: 3.7
services: docker

env:
  global:
    - IMAGE_NAME=dhsncats/client-cert-update
    - DOCKER_USER=jsf9k
    - secure: "2vaWVm0QeMELEXK9xefvuT3ye5hFrhJpVWpMOubE9dMIFg8VXjfbhI2\
J0OjELunvAspfJ8vO9wLMTmPqOmrth7Q6PCoRPuuJtpsmdaR3Qg4S/f+oCg0KobTSfsENn\
nZ3Mbv74qOULAUTd2/x5b88L4k+B2aEoUc/mNTY1SpTLuJeOM0c/mx+y6kNLBE8pUevpvF\
nvo3YjXjFgXYZpTOD/0H/lJXli8zbo7auy+mlPHrJq0zbOIWsAuSuWeyDoPwBQXtHkPW37\
HkdhfB0xWdeSKfmpOwxmU9QONGDDYTXj1bzU2w1+zEeHeMGULp9Sv7v8v3cJe0d1+dIrh1\
lFI9cXoLR8H1gcAVL8mPakU2u+LsSL0eTTFrZ0caQ2mpev/Lvys1YzTZsnPNJU4mpupa1I\
blmqZ6SUE9aprr7GKamSE14e4WdEhgPZY7Wh0v/gI9qxXAM7jaFlVb0FFzzGy+MQOOCT5L\
uiIL3O2XfVMT6jK8Sf6RpYa6K/vwp5vHi3drF7OaL+e9DzhEzYP9V7vHqLsdV3Cu+eu/zZ\
Qr2+ZXQ84bhlU75wetFXV5XcsqaqmXarNfIssWa65rw0thA6gEWdruJxWit5vWoEvrbbNC\
otXEYI9K/PhG2PYDE/09/TW8YJT6j4ahc2SmaJVme8u31iJVdsByBVXAs61aROmCCx+k="

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - travis_scripts/build_docker_image.sh

deploy:
  - provider: script
    script: travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
      python: '3.7'
