version: '3.2'

secrets:
  scan_read_creds:
    file: secrets/scan_read_creds.yml
  aws_config:
    file: secrets/aws_config

services:
  update:
    image: 'dhsncats/client-cert-update:0.0.2'
    secrets:
      - source: scan_read_creds
        target: scan_read_creds.yml
      - source: aws_config
        target: aws_config
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=default
