version: '3.2'

services:
  update:
    command:
      - "--db-creds-file=/run/secrets/scan_read_creds.yml"
      - "--from=reports@cyber.dhs.gov"
      - "--to=fnr.bod@hq.dhs.gov"
      - "--cc=ncats-dev@beta.dhs.gov,ncats@hq.dhs.gov"
      - "--reply=ncats-dev@beta.dhs.gov"
      - >-
        --subject="Latest list of web hosts that require authentication
        via client certificates"
      - "--text=body.txt"
      - "--html=body.html"
      - "--log-level=info"
