---
version: "3.7"

# This Docker composition file is used to build and test the container

secrets:
  aws_config:
    file: ./src/secrets/aws_config
  scan_read_creds:
    file: ./src/secrets/scan_read_creds.yml

services:
  update:
    build:
      context: .
      dockerfile: Dockerfile
    image: cisagov/client-cert-update
    init: true
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=default
    secrets:
      - source: aws_config
        target: aws_config
      - source: scan_read_creds
        target: scan_read_creds.yml
