version: '3.2'

secrets:
  db_creds:
    file: secrets/db_creds.json
  aws_config:
    file: secrets/aws_config

services:
  update:
    image: 'dhsncats/client-cert-update:0.0.1'
    secrets:
      - source: db_creds
        target: db_creds.json
      - source: aws_config
        target: aws_config
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=default
